export default [
    // "",
    {
        title: "java",
        collapsable: true,
        children: [
            "Java概述.md",
            "基础语法.md",
            "面向对象.md",
            "集合.md",
            "IO流.md",
            "异常.md",
            "反射.md",
            "常用API.md",
            "并发编程.md",
            "JVM.md",
            "设计模式.md",
            // {title: "并发编程",collapsable: true,children:["设计模式.md","JVM.md","常用API.md"]},
        ],
    },
    {
        title: "框架相关",
        collapsable: true,
        children: [
            "Spring.md",
            "SpringMVC.md",
            "MyBatis.md",
            "SpringBoot.md",
        ],
    },
    {
        title: "数据库相关",
        collapsable: true,
        children: [
            "Java概述.md",
            "基础语法.md",
            "面向对象.md",
            "集合.md",
            "IO流.md",
            "异常.md",
            "反射.md",
            "常用API.md",
            "并发编程.md",
            "JVM.md",
        ],
    },
    {
        title: "中间件相关",
        collapsable: true,
        children: [
            "Java概述.md",
            "基础语法.md",
            "面向对象.md",
            "集合.md",
            "IO流.md",
            "异常.md",
            "反射.md",
            "常用API.md",
            "并发编程.md",
            "JVM.md",
        ],
    },
    {
        title: "微服务相关",
        collapsable: true,
        children: [
            "Java概述.md",
            "基础语法.md",
            "面向对象.md",
            "集合.md",
            "IO流.md",
            "异常.md",
            "反射.md",
            "常用API.md",
            "并发编程.md",
            "JVM.md",
        ],
    },
    {
        title: "分布式相关",
        collapsable: true,
        children: [
            "Java概述.md",
            "基础语法.md",
            "面向对象.md",
            "集合.md",
            "IO流.md",
            "异常.md",
            "反射.md",
            "常用API.md",
            "并发编程.md",
            "JVM.md",
        ],
    },
];
